//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18444
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Const
{
	public enum CharacterState 
	{
		GROUNDED = 0,
		WALLED_FRONT,
		WALLED_BACK,
		JUMPING_UP,
		FALLING,
		WALL_JUMPING,
		WALL_WALKED_LEFT,
		WALL_WALKED_RIGHT,
		WALL_WALKING
	};

	public enum Direction
	{
		RIGHT = 1,
		LEFT = -1
	};

	public enum Facing
	{
		FRONT = 0,
		BACK = 1
	};

    public enum eTileType
    {
        DIRT,
        STONE,

        MAX
    }
}

