//------------------------------------------------------------------------------
// <auto-generated>
//     코드�구륬용�여 �성�었�니
//     ��버전:4.0.30319.18444
//
//     �일 �용변경하멘못�작발생�으� 코드륤시 �성�면
//     �러변겴용�실�니
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Const
{
    public enum GameState
    {
        IN_MENU,
        SETTING_PLAYER,
        PLAYING
    }

    public enum InputKeyFocus
    {
        CHAT_WINDOW,
        PLAYER,
        TEAM_SELECTOR,
        JOB_SELECTOR,
        NAME_SELECTOR
    }

    public enum InputMouseFocus
    {
        CHAT_WINDOW,
        PLAYER,
        TEAM_SELECTOR,
        JOB_SELECTOR,
        NAME_SELECTOR
    }

    public enum ChatState
    {
        NONE,
        WRITING,
        NEW_MESSAGE
    }

    public enum NameSelectorState
    {
        ON,
        OFF
    }

    public enum TeamSelectorState
    {
        ON,
        OFF
    }

    public enum JobSelectorState
    {
        ON,
        OFF
    }

    public enum MenuState
    {
        ON,
        OFF
    }

    public enum Team
    {
        NONE,
        BLUE,
        RED
    }

    public enum Job
    {
        SCOUT,
        HEAVY_GUNNER
    }

    public enum PlayerStatus
    {
        NONE,
        OBSERVING,
        PLAYING
    }

    public enum PlayerSettingError
    {
        NONE,
        ID,
        NAME,
        TEAM,
    }

    public enum PlayerSettingColumn
    {
        ID,
        NAME,
        TEAM,
        STATUS
    }

    
    //Unique State.
	public enum CharacterState 
	{
        DEAD = -1,
		GROUNDED = 0,
		JUMPING_UP,
		FALLING,
		WALL_JUMPING,
		WALL_WALKING
	};

    //Can have multiple state at the same time.
    public enum CharacterEnv
    {
        WALLED_FRONT,
        WALLED_BACK,
        WALL_WALKED_LEFT,
        WALL_WALKED_RIGHT,
    };

	public enum Direction
	{
		RIGHT = 1,
		LEFT = -1
	};

	public enum Facing
	{
		FRONT = 0,
		BACK = 1
	};

    public enum TileType
    {
        DIRT,
        STONE,

        MAX
    }

    public enum WeaponType
    {
        GUN,
        MISSLE,

        MAX
    }

    public enum AmmoType
    {
        NORMAL,
        INFINITE
    }
}

