//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18444
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

public class Game : MonoBehaviour
{
    private static Game instance;

    public bool is_initialized { get { return instance != null; } }

	public GameObject mapObject;
	public GameObject netManagerObject;
	public Vector3 spawnPosition;
	public GameObject playerPrefab;
	public Map m_map;

    public static Map map { get { return instance.m_map; } set { instance.m_map = value; } }

	PlayerBehaviour[] players;

	NetworkManager netManager;

    public void Init()
    {
        instance = this;
    }

	void Awake()
	{
        Init();
		players = new PlayerBehaviour[]{};
		netManager = netManagerObject.GetComponent<NetworkManager> ();
	}
    
	public GameObject MakeNetworkPlayer_instance()
	{
		return (GameObject)Network.Instantiate (playerPrefab, spawnPosition, Quaternion.identity, 0);

	}

	public void spawnNetworkPlayer_instance(NetworkPlayer client)
	{
		GameObject newPlayer = MakeNetworkPlayer ();

		newPlayer.networkView.RPC ("SetOwner", client);
	}

	public void drawMap(NetworkPlayer player)
	{
		map.drawMapNetwork (player);
	}

    public void ClearGame_instance()
    {
        foreach (PlayerBehaviour player in players)
        {
            Network.Destroy(player.gameObject);
        }
    }

    public static GameObject MakeNetworkPlayer()
    {
        return instance.MakeNetworkPlayer_instance();
    }

    public static void spawnNetworkPlayer(NetworkPlayer client)
    {
        instance.spawnNetworkPlayer_instance(client);
    }

    public static void ClearGame()
    {
        instance.ClearGame_instance();
    }
}